package br.com.autospec.backend.modules.report.service;

import br.com.autospec.backend.modules.vehicle.dto.VehicleCompareResponseDTO;
import br.com.autospec.backend.modules.vehicle.dto.VehicleResponseDTO;
import com.lowagie.text.*;
import com.lowagie.text.Font;
import com.lowagie.text.pdf.*;
import com.lowagie.text.pdf.draw.LineSeparator;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.awt.*;
import java.io.ByteArrayOutputStream;
import java.math.BigDecimal;
import java.time.format.DateTimeFormatter;
import java.time.LocalDateTime;

@Component
@Slf4j
public class PdfReportGenerator {

    private static final Color COLOR_BRAND    = new Color(0xE8, 0x6D, 0x13); // AutoSpec orange
    private static final Color COLOR_DARK     = new Color(0x1A, 0x1A, 0x2E);
    private static final Color COLOR_LIGHT_BG = new Color(0xF5, 0xF5, 0xF5);
    private static final Color COLOR_TEXT     = new Color(0x33, 0x33, 0x33);

    private static final Font FONT_TITLE   = new Font(Font.HELVETICA, 20, Font.BOLD,   COLOR_DARK);
    private static final Font FONT_SECTION = new Font(Font.HELVETICA, 13, Font.BOLD,   COLOR_BRAND);
    private static final Font FONT_HEADER  = new Font(Font.HELVETICA, 10, Font.BOLD,   Color.WHITE);
    private static final Font FONT_BODY    = new Font(Font.HELVETICA, 10, Font.NORMAL, COLOR_TEXT);
    private static final Font FONT_SMALL   = new Font(Font.HELVETICA,  8, Font.NORMAL, Color.GRAY);
    private static final Font FONT_WINNER  = new Font(Font.HELVETICA, 10, Font.BOLD,   COLOR_BRAND);

    public byte[] generateComparisonPdf(VehicleCompareResponseDTO comparison) {
        try (ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
            Document doc = new Document(PageSize.A4, 40, 40, 50, 50);
            PdfWriter writer = PdfWriter.getInstance(doc, baos);
            writer.setPageEvent(new PageFooter());
            doc.open();

            addHeader(doc, comparison.vehicleA(), comparison.vehicleB());
            doc.add(Chunk.NEWLINE);
            addExecutiveSummary(doc, comparison);
            doc.add(Chunk.NEWLINE);
            addSpecTable(doc, comparison.vehicleA(), comparison.vehicleB());
            doc.add(Chunk.NEWLINE);
            addKeyInsights(doc, comparison);

            doc.close();
            return baos.toByteArray();
        } catch (Exception e) {
            log.error("Erro ao gerar PDF de comparação", e);
            throw new RuntimeException("Falha na geração do PDF", e);
        }
    }

    public byte[] generateDossierPdf(VehicleResponseDTO vehicle) {
        try (ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
            Document doc = new Document(PageSize.A4, 40, 40, 50, 50);
            PdfWriter writer = PdfWriter.getInstance(doc, baos);
            writer.setPageEvent(new PageFooter());
            doc.open();

            addDossierHeader(doc, vehicle);
            doc.add(Chunk.NEWLINE);
            addDossierSpecTable(doc, vehicle);

            doc.close();
            return baos.toByteArray();
        } catch (Exception e) {
            log.error("Erro ao gerar PDF de dossier", e);
            throw new RuntimeException("Falha na geração do PDF", e);
        }
    }

    private void addHeader(Document doc, VehicleResponseDTO a, VehicleResponseDTO b) throws DocumentException {
        Paragraph title = new Paragraph("Comprehensive Comparison Report", FONT_TITLE);
        title.setAlignment(Element.ALIGN_CENTER);
        doc.add(title);

        Paragraph sub = new Paragraph(
                a.brand() + " " + a.model() + " " + a.year()
                        + "  vs.  "
                        + b.brand() + " " + b.model() + " " + b.year(),
                new Font(Font.HELVETICA, 12, Font.NORMAL, COLOR_BRAND));
        sub.setAlignment(Element.ALIGN_CENTER);
        doc.add(sub);

        Paragraph date = new Paragraph(
                "Generated by AutoSpec on " + LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")),
                FONT_SMALL);
        date.setAlignment(Element.ALIGN_CENTER);
        doc.add(date);

        LineSeparator sep = new LineSeparator(1f, 100f, COLOR_BRAND, Element.ALIGN_CENTER, -2f);
        doc.add(new Chunk(sep));
    }

    private void addDossierHeader(Document doc, VehicleResponseDTO v) throws DocumentException {
        Paragraph title = new Paragraph("Vehicle History Dossier", FONT_TITLE);
        title.setAlignment(Element.ALIGN_CENTER);
        doc.add(title);

        Paragraph sub = new Paragraph(
                v.brand() + " " + v.model() + " " + v.version() + " (" + v.year() + ")",
                new Font(Font.HELVETICA, 12, Font.NORMAL, COLOR_BRAND));
        sub.setAlignment(Element.ALIGN_CENTER);
        doc.add(sub);

        Paragraph date = new Paragraph(
                "Generated by AutoSpec on " + LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")),
                FONT_SMALL);
        date.setAlignment(Element.ALIGN_CENTER);
        doc.add(date);

        LineSeparator sep = new LineSeparator(1f, 100f, COLOR_BRAND, Element.ALIGN_CENTER, -2f);
        doc.add(new Chunk(sep));
    }

    private void addExecutiveSummary(Document doc, VehicleCompareResponseDTO comparison) throws DocumentException {
        doc.add(new Paragraph("Executive Summary", FONT_SECTION));

        String winner = switch (comparison.comparison().winner()) {
            case VEHICLE_A -> comparison.vehicleA().brand() + " " + comparison.vehicleA().model();
            case VEHICLE_B -> comparison.vehicleB().brand() + " " + comparison.vehicleB().model();
            default        -> "Draw";
        };

        String summaryText = comparison.summary() != null
                ? comparison.summary()
                : "Overall winner based on specification analysis: " + winner + ". "
                  + "Score — " + comparison.vehicleA().model() + ": " + comparison.comparison().scoreA()
                  + " pts  |  " + comparison.vehicleB().model() + ": " + comparison.comparison().scoreB() + " pts.";

        Paragraph p = new Paragraph(summaryText, FONT_BODY);
        p.setSpacingBefore(4f);
        doc.add(p);
    }

    private void addSpecTable(Document doc, VehicleResponseDTO a, VehicleResponseDTO b) throws DocumentException {
        doc.add(new Paragraph("Specification Match-up", FONT_SECTION));

        PdfPTable table = new PdfPTable(3);
        table.setWidthPercentage(100);
        table.setSpacingBefore(6f);
        table.setWidths(new float[]{40f, 30f, 30f});

        addTableHeader(table, "Specification", a.brand() + " " + a.model(), b.brand() + " " + b.model());

        addRow(table, "Engine",           a.engine(),                          b.engine());
        addRow(table, "Horsepower (hp)",  str(a.horsepower()),                 str(b.horsepower()));
        addRow(table, "Torque (Nm)",      str(a.torque()),                     str(b.torque()));
        addRow(table, "Top Speed (km/h)", str(a.topSpeed()),                   str(b.topSpeed()));
        addRow(table, "0–100 km/h (s)",   str(a.acceleration()),               str(b.acceleration()));
        addRow(table, "Drivetrain",        a.drivetrain(),                      b.drivetrain());
        addRow(table, "Weight (kg)",      str(a.weight()),                     str(b.weight()));
        addRow(table, "Price (USD)",      str(a.price()),                      str(b.price()));
        addRow(table, "Electric Range",   str(a.electricRange()),              str(b.electricRange()));
        addRow(table, "Dimensions L×W×H",
                fmt(a.length()) + " × " + fmt(a.width()) + " × " + fmt(a.height()),
                fmt(b.length()) + " × " + fmt(b.width()) + " × " + fmt(b.height()));

        doc.add(table);
    }

    private void addDossierSpecTable(Document doc, VehicleResponseDTO v) throws DocumentException {
        doc.add(new Paragraph("Technical Specifications", FONT_SECTION));

        PdfPTable table = new PdfPTable(2);
        table.setWidthPercentage(80);
        table.setSpacingBefore(6f);
        table.setHorizontalAlignment(Element.ALIGN_LEFT);
        table.setWidths(new float[]{50f, 50f});

        addTableHeader(table, "Attribute", "Value");
        addRow(table, "Brand",           v.brand());
        addRow(table, "Model",           v.model());
        addRow(table, "Version",         v.version());
        addRow(table, "Year",            str(v.year()));
        addRow(table, "Engine",          v.engine());
        addRow(table, "Horsepower (hp)", str(v.horsepower()));
        addRow(table, "Torque (Nm)",     str(v.torque()));
        addRow(table, "Drivetrain",      v.drivetrain());
        addRow(table, "Top Speed (km/h)",str(v.topSpeed()));
        addRow(table, "0–100 km/h (s)", str(v.acceleration()));
        addRow(table, "Weight (kg)",     str(v.weight()));
        addRow(table, "Price (USD)",     str(v.price()));
        if (v.electricRange() != null)
            addRow(table, "Electric Range (km)", str(v.electricRange()));

        doc.add(table);
    }

    private void addKeyInsights(Document doc, VehicleCompareResponseDTO comparison) throws DocumentException {
        doc.add(new Paragraph("Key Insights", FONT_SECTION));

        VehicleResponseDTO a = comparison.vehicleA();
        VehicleResponseDTO b = comparison.vehicleB();

        if (a.horsepower() != null && b.horsepower() != null) {
            int diff = Math.abs(a.horsepower() - b.horsepower());
            String more  = a.horsepower() > b.horsepower() ? a.model() : b.model();
            addInsightRow(doc, "Power", more + " has " + diff + " hp more");
        }
        if (a.topSpeed() != null && b.topSpeed() != null) {
            int diff = Math.abs(a.topSpeed() - b.topSpeed());
            String faster = a.topSpeed() > b.topSpeed() ? a.model() : b.model();
            addInsightRow(doc, "Top Speed", faster + " is " + diff + " km/h faster");
        }
        if (a.acceleration() != null && b.acceleration() != null) {
            BigDecimal diff = a.acceleration().subtract(b.acceleration()).abs();
            String quicker  = a.acceleration().compareTo(b.acceleration()) < 0 ? a.model() : b.model();
            addInsightRow(doc, "Acceleration", quicker + " reaches 100 km/h " + diff + "s sooner");
        }
        if (a.price() != null && b.price() != null) {
            BigDecimal diff   = a.price().subtract(b.price()).abs();
            String cheaper    = a.price().compareTo(b.price()) < 0 ? a.model() : b.model();
            addInsightRow(doc, "Price", cheaper + " is $" + diff.toPlainString() + " less expensive");
        }
    }

    private void addInsightRow(Document doc, String label, String text) throws DocumentException {
        Paragraph p = new Paragraph();
        p.add(new Chunk("▸ " + label + ": ", FONT_WINNER));
        p.add(new Chunk(text, FONT_BODY));
        p.setSpacingBefore(2f);
        doc.add(p);
    }

    private void addTableHeader(PdfPTable table, String... cols) {
        for (String col : cols) {
            PdfPCell cell = new PdfPCell(new Phrase(col, FONT_HEADER));
            cell.setBackgroundColor(COLOR_DARK);
            cell.setPadding(6f);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cell);
        }
    }

    private void addRow(PdfPTable table, String label, String... values) {
        PdfPCell labelCell = new PdfPCell(new Phrase(label, FONT_BODY));
        labelCell.setPadding(5f);
        labelCell.setBackgroundColor(COLOR_LIGHT_BG);
        table.addCell(labelCell);

        for (String val : values) {
            PdfPCell c = new PdfPCell(new Phrase(val != null ? val : "—", FONT_BODY));
            c.setPadding(5f);
            c.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(c);
        }
    }

    private String str(Object v) { return v != null ? v.toString() : "N/A"; }
    private String fmt(BigDecimal v) { return v != null ? v.toPlainString() : "N/A"; }

    private static class PageFooter extends PdfPageEventHelper {
        private static final Font FOOTER_FONT = new Font(Font.HELVETICA, 8, Font.NORMAL, Color.GRAY);

        @Override
        public void onEndPage(PdfWriter writer, Document document) {
            PdfContentByte cb = writer.getDirectContent();
            Phrase footer = new Phrase(
                    "© " + java.time.Year.now().getValue()
                            + " AutoSpec Intelligence Platform  |  Page " + writer.getPageNumber(),
                    FOOTER_FONT);
            ColumnText.showTextAligned(cb, Element.ALIGN_CENTER, footer,
                    (document.left() + document.right()) / 2,
                    document.bottom() - 10, 0);
        }
    }
}
